# Use an official Node runtime as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY app/package*.json ./

# Install dependencies including MUI and related packages
# RUN npm install --verbose && \
#     npm install @mui/material @emotion/react @emotion/styled && \
#     npm install @mui/material @mui/styled-engine-sc styled-components && \
#     npm install @fontsource/roboto && \

# Install dependencies
RUN npm install --verbose

# Copy the rest of the application code to the working directory
COPY app ./

# Expose the default port 8080 (webpack) to the outside world 
EXPOSE 8080

# Start the React application
CMD ["npm", "start"]
